### ISSUE TITLE
sorry for noob question im just new on this

### ISSUE THREAD

**Issue by jarz54** [nozwock/yanu#47] opened 2024-03-20 16:55 UTC
how to put this update,its my problem my internal storage is too small for the nsp file im patching i want to patch it in external storage but it yanu cant read or locate the the folder path from the sd card
i just read on this update that it supports the external storage location no need to move to internal,but i don't know how to build this version on yanu on termux, please help

**Comment by nozwock** [comment] 2024-05-28 19:43
Duplicate of #48

**Closed by nozwock** 2024-05-28 19:43 UTC
