### ISSUE TITLE
Fails to update to Skyrim 1.1.177.3285177

### ISSUE THREAD

**Issue by Loganbogan9** [nozwock/yanu#7] opened 2023-03-22 16:26 UTC
When trying to update Skyrim NSP, the tool fails to extract the base Skyrim NSP. The error output it gives goes as follows:

"PFS0:
Magic:                              PFS0
Number of files:                    6
Files:                              pfs0:/3cad207409bec099fbbf02548bdf4d6b.nca
                                    pfs0:/52b98696777222a184a54e56222d24ac.nca
                                    pfs0:/a34ebd3c9d2787c3aa9a451bede93f5d.nca
                                    pfs0:/0982738232945779ed215f8badb091da.cnmt.nca
                                    pfs0:/01000a10041ea0000000000000000003.tik
                                    pfs0:/01000a10041ea0000000000000000003.cert

/3cad207409bec099fbbf02548bdf4d6b.nca
Error:
   0: Failed to extract "C:\\Users\\iamlo\\Downloads\\Elder\\Skyrim00.nsp"

Location:
   C:\Users\user\Desktop\yanu\src\hac\rom.rs:83"

I'm on Windows. The base Skyrim file is ver. 1.0.12.517175 and the Update file is 1.1.177.3285177

**Comment by nozwock** [comment] 2023-03-22 16:33
This isn't really helpful, send the logs like this:

```html
<details>
<summary>Logs</summary>
copy paste the logs here!
</details>
```

Also, maybe try the previous 0.6.0 version after deleting the [configs folder](https://github.com/nozwock/yanu#directories-used).
See if the issue also exists on 0.6.0

**Comment by Loganbogan9** [comment] 2023-03-22 16:49
> This isn't really helpful, send the relevant logs like this:
> 
> ```
> <details>
> <summary>Logs</summary>
> copy paste the logs here!
> </details>
> ```
> 
> Also, maybe try the previous `0.6.0` version after deleting the [configs folder](https://github.com/nozwock/yanu#directories-used). See if the issue also exists on `0.6.0`; I might've introduced a regression in `0.6.1`

Ah, sorry, I'm not familiar with making Github errors, so I apologize on the lack of details. I reverted back to 0.6.0 and as you suggested, it worked without a hitch. The only problem now is that the update didn't extract. I theorize though that this could be because newer Skyrim updates have the DLC files within them, so I'll try one before anniversary edition came out. Thanks!

**Comment by nozwock** [comment] 2023-03-22 16:53
> I reverted back to 0.6.0 and as you suggested, it worked without a hitch.\
Thanks for checking, looks like I've indeed introduced a regression. I'll fix this later as I'm busy rn. Let others also know to revert to `0.6.0` for now.

> I theorize though that this could be because newer Skyrim updates have the DLC files within them\
It could be the case. I don't have it, so can't test.

**Comment by nozwock** [comment] 2023-03-22 16:58
This is likely related to changes regarding `title.keys` handling and seems to only affect PC builds (they're using `hactoolnet`).

**Comment by Loganbogan9** [comment] 2023-03-22 17:15
> This is likely related to changes regarding `title.keys` handling and seems to only affect PC builds (they're using `hactoolnet`).

Interesting. After using an older update it was able to extract them all but Then

**Comment by Loganbogan9** [comment] 2023-03-22 17:16
> This is likely related to changes regarding `title.keys` handling and seems to only affect PC builds (they're using `hactoolnet`).

Interesting. I don't know if this is separate or not, but I was able to extract an older update but then it threw an error building it back into an NSP.

**Comment by nozwock** [comment] 2023-03-22 17:19
No need, I'll close this when it's fixed.

**Comment by nozwock** [comment] 2023-03-25 14:49
Renaming as it doesn't seems to be related to changes for `title.keys`

**Comment by nozwock** [comment] 2023-03-25 14:50
Logs are needed to make progress on this issue.

**Comment by nozwock** [comment] 2023-03-25 15:19
Had someone test Skyrim with yanu just now, it's working fine. I don't know what's up with you....well you didn't even send logs so can't help.
![Screenshot_20230326_000915_skyline emu](https://user-images.githubusercontent.com/57829219/227726150-4a1fdd8d-1a30-4027-be83-8afea327d669.jpg)

<details>
<summary>Logs</summary>

```
2023-03-25T14:28:39.513630Z  INFO yanu: Launching yanu on windows!
2023-03-25T14:28:39.513657Z  INFO yanu: version="0.6.1"
2023-03-25T14:29:41.601672Z  INFO yanu::utils: Selected file path="E:\\SWITCH\\Ingame\\The Elder Scrolls V Skyrim.nsp"
2023-03-25T14:29:51.458410Z  INFO yanu::utils: Selected file path="E:\\SWITCH\\Updates\\The Elder Scrolls V Skyrim [01000A10041EA800][v262144].nsp"
2023-03-25T14:29:52.350454Z  INFO yanu: Started patching!
2023-03-25T14:29:52.370126Z  INFO yanu::hac::rom: Extracting self.path="E:\\SWITCH\\Ingame\\The Elder Scrolls V Skyrim.nsp"
2023-03-25T14:32:57.392364Z  INFO yanu::hac::rom: Extraction done self.path="E:\\SWITCH\\Ingame\\The Elder Scrolls V Skyrim.nsp" to="E:\\SWITCH\\.tmpBdSDja"
2023-03-25T14:32:57.829578Z  INFO yanu::hac::rom: Extracting self.path="E:\\SWITCH\\Updates\\The Elder Scrolls V Skyrim [01000A10041EA800][v262144].nsp"
2023-03-25T14:34:29.602764Z  INFO yanu::hac::rom: Extraction done self.path="E:\\SWITCH\\Updates\\The Elder Scrolls V Skyrim [01000A10041EA800][v262144].nsp" to="E:\\SWITCH\\.tmpRDgFUS"
2023-03-25T14:34:29.641173Z  INFO yanu::hac::rom: Deriving TitleKey nsp="E:\\SWITCH\\Ingame\\The Elder Scrolls V Skyrim.nsp"
2023-03-25T14:34:29.641350Z  INFO yanu::hac::ticket: Reading ticket tik="E:\\SWITCH\\.tmpBdSDja\\01000a10041ea0000000000000000003.tik"
2023-03-25T14:34:29.730876Z  INFO yanu::hac::rom: Derived TitleKey successfully!
2023-03-25T14:34:29.730879Z  INFO yanu::hac::rom: Deriving TitleKey nsp="E:\\SWITCH\\Updates\\The Elder Scrolls V Skyrim [01000A10041EA800][v262144].nsp"
2023-03-25T14:34:29.731042Z  INFO yanu::hac::ticket: Reading ticket tik="E:\\SWITCH\\.tmpRDgFUS\\01000a10041ea800000000000000000e.tik"
2023-03-25T14:34:29.731116Z  INFO yanu::hac::rom: Derived TitleKey successfully!
2023-03-25T14:34:29.731118Z  INFO yanu::hac::patch: Storing TitleKeys keyfile="C:\\Users\\kimchi\\.switch\\title.keys"
2023-03-25T14:34:30.266139Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpBdSDja\\3cad207409bec099fbbf02548bdf4d6b.nca"
2023-03-25T14:34:31.031390Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.033840Z DEBUG yanu::hac::rom: content_type=Some(Program)
2023-03-25T14:34:31.033915Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpBdSDja\\52b98696777222a184a54e56222d24ac.nca"
2023-03-25T14:34:31.075696Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.075716Z DEBUG yanu::hac::rom: content_type=Some(Control)
2023-03-25T14:34:31.075801Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpBdSDja\\a34ebd3c9d2787c3aa9a451bede93f5d.nca"
2023-03-25T14:34:31.106512Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.106530Z DEBUG yanu::hac::rom: content_type=Some(Manual)
2023-03-25T14:34:31.106603Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpBdSDja\\0982738232945779ed215f8badb091da.cnmt.nca"
2023-03-25T14:34:31.136228Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.136246Z DEBUG yanu::hac::rom: content_type=Some(Meta)
2023-03-25T14:34:31.136258Z DEBUG yanu::hac::patch: base_nca=Nca { path: "E:\\SWITCH\\.tmpBdSDja\\3cad207409bec099fbbf02548bdf4d6b.nca", title_id: Some("01000A10041EA000"), content_type: Program }
2023-03-25T14:34:31.136811Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpRDgFUS\\3b904a3fbceb1def9cf64369a5206543.nca"
2023-03-25T14:34:31.176252Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.176269Z DEBUG yanu::hac::rom: content_type=Some(Program)
2023-03-25T14:34:31.176338Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpRDgFUS\\9f4483c0c8c4e2f761a750486a428845.nca"
2023-03-25T14:34:31.203922Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.203941Z DEBUG yanu::hac::rom: content_type=Some(Control)
2023-03-25T14:34:31.204013Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpRDgFUS\\8fda11250ef7c5c6a917983e642232cc.nca"
2023-03-25T14:34:31.227901Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:34:31.227920Z DEBUG yanu::hac::rom: content_type=Some(Manual)
2023-03-25T14:34:31.227992Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpRDgFUS\\ce3b95611e5e9af1ebd92cb3bc94555a.cnmt.nca"
2023-03-25T14:34:31.249682Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA800")
2023-03-25T14:34:31.249698Z DEBUG yanu::hac::rom: content_type=Some(Meta)
2023-03-25T14:34:31.249711Z DEBUG yanu::hac::patch: update_nca=Nca { path: "E:\\SWITCH\\.tmpRDgFUS\\3b904a3fbceb1def9cf64369a5206543.nca", title_id: Some("01000A10041EA000"), content_type: Program }
2023-03-25T14:34:31.249717Z DEBUG yanu::hac::patch: control_nca=Nca { path: "E:\\SWITCH\\.tmpRDgFUS\\9f4483c0c8c4e2f761a750486a428845.nca", title_id: Some("01000A10041EA000"), content_type: Control }
2023-03-25T14:34:31.250260Z  INFO yanu::hac::rom: Extracting self.path="E:\\SWITCH\\.tmpBdSDja\\3cad207409bec099fbbf02548bdf4d6b.nca" aux.path="E:\\SWITCH\\.tmpRDgFUS\\3b904a3fbceb1def9cf64369a5206543.nca"
2023-03-25T14:37:16.117864Z  INFO yanu::hac::rom: Extraction done self.path="E:\\SWITCH\\.tmpBdSDja\\3cad207409bec099fbbf02548bdf4d6b.nca" romfs="E:\\SWITCH\\.tmpM4chFF\\romfs" exefs="E:\\SWITCH\\.tmpM4chFF\\exefs"
2023-03-25T14:37:16.125883Z  INFO yanu::hac::patch: Cleaning up dir="E:\\SWITCH\\.tmpBdSDja"
2023-03-25T14:37:16.375855Z  INFO yanu::hac::patch: Cleaning up dir="E:\\SWITCH\\.tmpRDgFUS"
2023-03-25T14:37:16.580858Z  INFO yanu::hac::rom: Packing romfs="E:\\SWITCH\\.tmpM4chFF\\romfs" exefs="E:\\SWITCH\\.tmpM4chFF\\exefs" to="E:\\SWITCH\\.tmpM4chFF\\nca"
2023-03-25T14:56:59.030495Z  INFO yanu::hac::rom: Packing done outdir="E:\\SWITCH\\.tmpM4chFF\\nca"
2023-03-25T14:56:59.066782Z  INFO yanu::hac::rom: Identifying TitleID and ContentType nca="E:\\SWITCH\\.tmpM4chFF\\nca\\4d09b9f308ebb2e92365b7e04bf8e6bb.nca"
2023-03-25T14:56:59.324781Z DEBUG yanu::hac::rom: title_id=Some("01000A10041EA000")
2023-03-25T14:56:59.324800Z DEBUG yanu::hac::rom: content_type=Some(Program)
2023-03-25T14:56:59.324942Z  INFO yanu::hac::rom: Generating Meta NCA program.path="E:\\SWITCH\\.tmpM4chFF\\nca\\4d09b9f308ebb2e92365b7e04bf8e6bb.nca" control.path="E:\\SWITCH\\.tmpM4chFF\\nca\\9f4483c0c8c4e2f761a750486a428845.nca"
2023-03-25T14:59:08.439419Z  INFO yanu::hac::rom: Generated Meta NCA outdir="E:\\SWITCH\\.tmpM4chFF\\nca"
2023-03-25T14:59:08.439936Z  INFO yanu::hac::rom: Packing NCAs to NSP nca_dir="E:\\SWITCH\\.tmpM4chFF\\nca"
2023-03-25T15:01:41.753456Z  INFO yanu::hac::rom: Packed NCAs to NSP outdir="E:\\SWITCH"
2023-03-25T15:01:41.753483Z  INFO yanu::hac::patch: Moving from="E:\\SWITCH\\01000a10041ea000.nsp" to="E:\\SWITCH\\01000a10041ea000[yanu-patched].nsp"
2023-03-25T15:01:44.944454Z  INFO yanu: Done
```

</details>

**Closed by nozwock** 2023-03-25 15:19 UTC
Labels: bug
